
#日志
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      sl:
        dao: debug
    root: info
#端口号
server:
  port: 1214


spring:
  redis:
    database: 15
    host: 127.0.0.1
    password:
    port: 6379

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1


