
#日志
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      sl:
        dao: debug
    root: info
#端口号
server:
  port: 1213

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）
  redis:
    database: 15
    host: 127.0.0.1
    password:
    port: 6379

exclusion:
  url:
    - /pub/health
    - /login





